[package]
name = "rust-sfml"
version = "0.1.0"
authors = ["dav"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
sfml = "0.16.0"
